### PR TITLE
Set up a "Hello world" project

### PR DESCRIPTION
**Pull request by Tafloninno**
- Create a new Rails app called 'hello-rails-react'.

      Use the command rails new -j webpack my_new_rails_app as described in the previous lesson's tutorial.

- Verify that the jsbundling-rails gem is added to your Gemfile.

- Initialize your project with Git.

- Install needed node dependencies as described in the previous lesson's tutorial.
- Create a babel.config.js in the root folder of your project as described in the previous lesson's tutorial.
- Update webpack.config.js to include the babel loader as described in the previous lesson's tutorial.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails 
   route).
- Create a static view that will be the root of your app.
- Create the App component with react-router and render it in your static view.
- Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- Display the random greeting in your Greeting component.

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
Hi @Tafloninno 🤝 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a re-review without the previous reviews, from your notes: `Hello, i had to create another repo because my previous one had conflicting files that could not enable me fetch the api and display it to the browser` 👉🏽 I would encourage you to try resolve the conflicts at any cost for you to learn this skill since it is even valuable in real job as well, or if that doesn't work after you try whatever seek for a help, or if everything doesn't serve you any help please add link to the previous PR where other previous reviews have been performed for the sake of easy re-reviewing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Tafloninno** [comment]
@descholar-ceo Thanks for the review and the clarity but unfortunately the previous repo with the previous review doesn't exist (it has been deleted).

**Review by Gambit142 — APPROVED** [review]
Hi @Tafloninno 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- All linter checks passed ✔️ 
- Use of `jsbundling-rails` gem ✔️ 
- Configured backend properly ✔️ 
- Use of react and redux ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Tafloninno** [comment]
@Gambit142 Thank you for your kind review

**Pull request merged**
